// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: testmessage.proto

package td

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type S_Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *S_Example) Reset() {
	*x = S_Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S_Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S_Example) ProtoMessage() {}

func (x *S_Example) ProtoReflect() protoreflect.Message {
	mi := &file_testmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S_Example.ProtoReflect.Descriptor instead.
func (*S_Example) Descriptor() ([]byte, []int) {
	return file_testmessage_proto_rawDescGZIP(), []int{0}
}

func (x *S_Example) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type G_Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *G_Example) Reset() {
	*x = G_Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G_Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G_Example) ProtoMessage() {}

func (x *G_Example) ProtoReflect() protoreflect.Message {
	mi := &file_testmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G_Example.ProtoReflect.Descriptor instead.
func (*G_Example) Descriptor() ([]byte, []int) {
	return file_testmessage_proto_rawDescGZIP(), []int{1}
}

func (x *G_Example) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type P_Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *P_Example) Reset() {
	*x = P_Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_Example) ProtoMessage() {}

func (x *P_Example) ProtoReflect() protoreflect.Message {
	mi := &file_testmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_Example.ProtoReflect.Descriptor instead.
func (*P_Example) Descriptor() ([]byte, []int) {
	return file_testmessage_proto_rawDescGZIP(), []int{2}
}

func (x *P_Example) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TEST_Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TEST_Example) Reset() {
	*x = TEST_Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TEST_Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TEST_Example) ProtoMessage() {}

func (x *TEST_Example) ProtoReflect() protoreflect.Message {
	mi := &file_testmessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TEST_Example.ProtoReflect.Descriptor instead.
func (*TEST_Example) Descriptor() ([]byte, []int) {
	return file_testmessage_proto_rawDescGZIP(), []int{3}
}

func (x *TEST_Example) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_testmessage_proto protoreflect.FileDescriptor

var file_testmessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x09, 0x53, 0x5f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x47, 0x5f, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x09, 0x50, 0x5f, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c,
	0x54, 0x45, 0x53, 0x54, 0x5f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x69, 0x61, 0x6e, 0x6b, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x2f, 0x6e, 0x65, 0x74,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testmessage_proto_rawDescOnce sync.Once
	file_testmessage_proto_rawDescData = file_testmessage_proto_rawDesc
)

func file_testmessage_proto_rawDescGZIP() []byte {
	file_testmessage_proto_rawDescOnce.Do(func() {
		file_testmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_testmessage_proto_rawDescData)
	})
	return file_testmessage_proto_rawDescData
}

var file_testmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testmessage_proto_goTypes = []interface{}{
	(*S_Example)(nil),    // 0: S_Example
	(*G_Example)(nil),    // 1: G_Example
	(*P_Example)(nil),    // 2: P_Example
	(*TEST_Example)(nil), // 3: TEST_Example
}
var file_testmessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testmessage_proto_init() }
func file_testmessage_proto_init() {
	if File_testmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S_Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G_Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TEST_Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testmessage_proto_goTypes,
		DependencyIndexes: file_testmessage_proto_depIdxs,
		MessageInfos:      file_testmessage_proto_msgTypes,
	}.Build()
	File_testmessage_proto = out.File
	file_testmessage_proto_rawDesc = nil
	file_testmessage_proto_goTypes = nil
	file_testmessage_proto_depIdxs = nil
}
