// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: pipe.proto

package pipe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestClient is the client API for Rest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestClient interface {
	Get(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*anypb.Any, error)
	Post(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type restClient struct {
	cc grpc.ClientConnInterface
}

func NewRestClient(cc grpc.ClientConnInterface) RestClient {
	return &restClient{cc}
}

func (c *restClient) Get(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*anypb.Any, error) {
	out := new(anypb.Any)
	err := c.cc.Invoke(ctx, "/Rest/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restClient) Post(ctx context.Context, in *anypb.Any, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Rest/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestServer is the server API for Rest service.
// All implementations must embed UnimplementedRestServer
// for forward compatibility
type RestServer interface {
	Get(context.Context, *anypb.Any) (*anypb.Any, error)
	Post(context.Context, *anypb.Any) (*emptypb.Empty, error)
	mustEmbedUnimplementedRestServer()
}

// UnimplementedRestServer must be embedded to have forward compatible implementations.
type UnimplementedRestServer struct {
}

func (UnimplementedRestServer) Get(context.Context, *anypb.Any) (*anypb.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRestServer) Post(context.Context, *anypb.Any) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedRestServer) mustEmbedUnimplementedRestServer() {}

// UnsafeRestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestServer will
// result in compilation errors.
type UnsafeRestServer interface {
	mustEmbedUnimplementedRestServer()
}

func RegisterRestServer(s grpc.ServiceRegistrar, srv RestServer) {
	s.RegisterService(&Rest_ServiceDesc, srv)
}

func _Rest_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(anypb.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rest/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServer).Get(ctx, req.(*anypb.Any))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rest_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(anypb.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rest/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServer).Post(ctx, req.(*anypb.Any))
	}
	return interceptor(ctx, in, info, handler)
}

// Rest_ServiceDesc is the grpc.ServiceDesc for Rest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rest",
	HandlerType: (*RestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Rest_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Rest_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pipe.proto",
}

// KeepaliveClient is the client API for Keepalive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeepaliveClient interface {
	Link(ctx context.Context, opts ...grpc.CallOption) (Keepalive_LinkClient, error)
}

type keepaliveClient struct {
	cc grpc.ClientConnInterface
}

func NewKeepaliveClient(cc grpc.ClientConnInterface) KeepaliveClient {
	return &keepaliveClient{cc}
}

func (c *keepaliveClient) Link(ctx context.Context, opts ...grpc.CallOption) (Keepalive_LinkClient, error) {
	stream, err := c.cc.NewStream(ctx, &Keepalive_ServiceDesc.Streams[0], "/Keepalive/Link", opts...)
	if err != nil {
		return nil, err
	}
	x := &keepaliveLinkClient{stream}
	return x, nil
}

type Keepalive_LinkClient interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ClientStream
}

type keepaliveLinkClient struct {
	grpc.ClientStream
}

func (x *keepaliveLinkClient) Send(m *anypb.Any) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keepaliveLinkClient) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeepaliveServer is the server API for Keepalive service.
// All implementations must embed UnimplementedKeepaliveServer
// for forward compatibility
type KeepaliveServer interface {
	Link(Keepalive_LinkServer) error
	mustEmbedUnimplementedKeepaliveServer()
}

// UnimplementedKeepaliveServer must be embedded to have forward compatible implementations.
type UnimplementedKeepaliveServer struct {
}

func (UnimplementedKeepaliveServer) Link(Keepalive_LinkServer) error {
	return status.Errorf(codes.Unimplemented, "method Link not implemented")
}
func (UnimplementedKeepaliveServer) mustEmbedUnimplementedKeepaliveServer() {}

// UnsafeKeepaliveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeepaliveServer will
// result in compilation errors.
type UnsafeKeepaliveServer interface {
	mustEmbedUnimplementedKeepaliveServer()
}

func RegisterKeepaliveServer(s grpc.ServiceRegistrar, srv KeepaliveServer) {
	s.RegisterService(&Keepalive_ServiceDesc, srv)
}

func _Keepalive_Link_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeepaliveServer).Link(&keepaliveLinkServer{stream})
}

type Keepalive_LinkServer interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ServerStream
}

type keepaliveLinkServer struct {
	grpc.ServerStream
}

func (x *keepaliveLinkServer) Send(m *anypb.Any) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keepaliveLinkServer) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Keepalive_ServiceDesc is the grpc.ServiceDesc for Keepalive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keepalive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Keepalive",
	HandlerType: (*KeepaliveServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Link",
			Handler:       _Keepalive_Link_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pipe.proto",
}
