// Code generated by protoc-gen-go. DO NOT EDIT.
// source: think.proto

/*
Package think is a generated protocol buffer package.

It is generated from these files:
	think.proto

It has these top-level messages:
	BUS
*/
package think

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BUS struct {
	Data *google_protobuf.Any `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *BUS) Reset()                    { *m = BUS{} }
func (m *BUS) String() string            { return proto.CompactTextString(m) }
func (*BUS) ProtoMessage()               {}
func (*BUS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BUS) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BUS)(nil), "BUS")
}

func init() { proto.RegisterFile("think.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xc8, 0xcc,
	0xcb, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x13, 0xf3, 0x2a, 0x21, 0x52, 0x4a, 0xfa, 0x5c, 0xcc, 0x4e,
	0xa1, 0xc1, 0x42, 0x1a, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0x22, 0x7a, 0x10, 0x0d, 0x7a, 0x30, 0x0d, 0x7a, 0x8e, 0x79, 0x95, 0x41, 0x60, 0x15, 0x49,
	0x6c, 0x60, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x02, 0xce, 0x39, 0x61, 0x00,
	0x00, 0x00,
}
