// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: net/pb/message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Message 用于服务间传输的消息，为了绑定Token，所以不直接传输data。服务名可直接通过data 获取，所以不再使用Key字段
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                           //NOTE: 关键字，用于标识消息发送目标
	SenderUid    uint64     `protobuf:"varint,2,opt,name=senderUid,proto3" json:"senderUid,omitempty"`              //NOTE: 发送者uid，如果是服务端发送，不填此参数
	ReceiverUids []uint64   `protobuf:"varint,3,rep,packed,name=receiverUids,proto3" json:"receiverUids,omitempty"` //NOTE: 接收者uid组，如果是全服发送，不填此参数，解析为全服发送
	Value        *anypb.Any `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                       //NTOE: 实际的数据
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_pb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_net_pb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_net_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Message) GetSenderUid() uint64 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *Message) GetReceiverUids() []uint64 {
	if x != nil {
		return x.ReceiverUids
	}
	return nil
}

func (x *Message) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_net_pb_message_proto protoreflect.FileDescriptor

var file_net_pb_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x73, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x61, 0x6e,
	0x6b, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_net_pb_message_proto_rawDescOnce sync.Once
	file_net_pb_message_proto_rawDescData = file_net_pb_message_proto_rawDesc
)

func file_net_pb_message_proto_rawDescGZIP() []byte {
	file_net_pb_message_proto_rawDescOnce.Do(func() {
		file_net_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_pb_message_proto_rawDescData)
	})
	return file_net_pb_message_proto_rawDescData
}

var file_net_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_net_pb_message_proto_goTypes = []interface{}{
	(*Message)(nil),   // 0: Message
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_net_pb_message_proto_depIdxs = []int32{
	1, // 0: Message.value:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_net_pb_message_proto_init() }
func file_net_pb_message_proto_init() {
	if File_net_pb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_pb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_pb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_pb_message_proto_goTypes,
		DependencyIndexes: file_net_pb_message_proto_depIdxs,
		MessageInfos:      file_net_pb_message_proto_msgTypes,
	}.Build()
	File_net_pb_message_proto = out.File
	file_net_pb_message_proto_rawDesc = nil
	file_net_pb_message_proto_goTypes = nil
	file_net_pb_message_proto_depIdxs = nil
}
