// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	AimTokens            []string `protobuf:"bytes,4,rep,name=aimTokens,proto3" json:"aimTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Message) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Message) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetAimTokens() []string {
	if m != nil {
		return m.AimTokens
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8c, 0xb1, 0x0e, 0xc2, 0x20,
	0x14, 0x45, 0x53, 0x5b, 0x35, 0xc5, 0x98, 0x18, 0xd2, 0x81, 0xaa, 0x43, 0xe3, 0xc4, 0x04, 0x89,
	0x7e, 0x81, 0xee, 0x2e, 0x8d, 0x93, 0x1b, 0x28, 0x52, 0x82, 0x85, 0x46, 0xe8, 0xc0, 0xdf, 0x9b,
	0x42, 0x8c, 0xdb, 0xbb, 0xf7, 0x9d, 0x7b, 0xc0, 0xba, 0x17, 0xce, 0x31, 0x29, 0xc8, 0xf0, 0xb1,
	0xde, 0x6e, 0x6b, 0x69, 0xad, 0x7c, 0x0b, 0x1a, 0x13, 0x1f, 0x5f, 0x94, 0x99, 0x90, 0x5e, 0x87,
	0x00, 0x96, 0xd7, 0xc4, 0xc2, 0x0d, 0xc8, 0xb5, 0x08, 0x28, 0x6b, 0x32, 0x5c, 0xb6, 0xd3, 0x09,
	0x2b, 0x30, 0xf7, 0x56, 0x0b, 0x83, 0x66, 0xb1, 0x4b, 0x01, 0x62, 0x50, 0x3c, 0x99, 0x67, 0x28,
	0x6f, 0x32, 0xbc, 0x3a, 0x56, 0x24, 0xc9, 0xc9, 0x4f, 0x4e, 0xce, 0x26, 0xb4, 0x91, 0x80, 0x7b,
	0x50, 0x32, 0xd5, 0xdf, 0xa6, 0x95, 0x43, 0x45, 0x93, 0xe3, 0xb2, 0xfd, 0x17, 0x97, 0xdd, 0xbd,
	0x96, 0xca, 0x77, 0x23, 0x27, 0x0f, 0xdb, 0xd3, 0x4e, 0x31, 0xa3, 0xa9, 0xef, 0x94, 0xd1, 0x74,
	0xe0, 0x7c, 0x11, 0x75, 0xa7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x74, 0x0a, 0x8a, 0xca,
	0x00, 0x00, 0x00,
}
